config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

app/views/shared/_dropdown.html.erb
<div class="dropdown-menu dropdown-menu-right">
  <button class="dropdown-item" type="button">
    <%= link_to "Dashboard", dashboard_path, class: "btn" %>
  </button>
  <button class="dropdown-item" type="button">
    <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn"%>
  </button>
  <div class="dropdown-divider"></div>
  <button class="dropdown-item " type="button">
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn" %>
  </button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 footer-logo-container">
        <%= image_tag("logo-white.png", alt: "Bibtome Logo", class: "logo logo-white") %>
        <p>Get your lost items returned easily, faster and securely. </p>
      </div>
      <div class="col-sm gutter-max">
        <h4>unternehmen</h4>
        <a href="#">Über uns</a>
        <a href="#">team</a>
        <a href="#">Kontakt</a>
      </div>
      <div class="col-sm gutter-max">
        <h4>rechtlich</h4>
        <a href="#">sicherheit</a>
        <a href="#">Datenschutz</a>
        <a href="#" class="text-uppercase">AGB</a>
      </div>
      <div class="col-sm">
        <h4>sozialen Medien</h4>
        <ul>
          <li>
            <a href="#"><%= image_tag("facebook-icon.png", alt: "facebook icon", class: "s-media-icons")%></a>
          </li>
          <li>
            <a href="#"><%= image_tag("instagram-icon.png", alt: "facebook icon", class: "s-media-icons")%></a>
          </li>
          <li>
            <a href="#"><%= image_tag("linkedin-icon.png", alt: "facebook icon", class: "s-media-icons")%></a>
          </li>
        </ul>
      </div>
    </div>
    <div class="copyright">Copyright ©2020 Bibto.me, All rights reserved.</div>
  </div>
</footer>

app/views/shared/_menu.html.erb
<body>
  <!-- Burger-Menu Icon -->
  <div class="burger-menu">
    <input type="checkbox" id="toggle">

    <label for="toggle" >
      <!-- <svg  viewbox="0 0 100 10 0" width="100%" height="100%" class="mt-2">
        <circle cx="50" cy="50"></circle>
      </svg> -->
      <div class="hamburger hamburger-blue" id="my-burger-menu">
        <div class="center"></div>
      </div>
    </label>
  </div>

  <!-- Sidebar Nav -->
  <div id="mySidenav" class="sidenav d-sm-none">
    <div class="noScroll">
      <% if current_user %>
        <a><%= link_to "Dashboard", dashboard_path, class: "border-bottom" %></a>
        <a><%= link_to "Return item", finder_input_path, class: "border-bottom" %></a>
        <a><%= link_to "Register tag", register_input_path, class: "border-bottom" %></a>
        <a><%= link_to "Home", root_path, class: "border-bottom" %></a>
        <a><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "border-bottom" %></a>
      <% else %>
        <a><%= link_to "Login", new_user_session_path, class: "border-bottom" %></a>
        <a><%= link_to "Create account", new_user_registration_path, class: "border-bottom" %></a>
        <a><%= link_to "Über uns", root_path, class: "border-bottom" %></a>
        <a><%= link_to "Team", root_path, class: "border-bottom" %></a>
        <a><%= link_to "Kontakt", root_path, class: "border-bottom" %></a>
        <a><%= link_to "Home", root_path, class: "border-bottom" %></a>
      <% end %>
    </div>
  </div>


  <script>
    let menu = document.querySelector( "#mySidenav" );
    let menuIcon = document.querySelector( "#my-burger-menu" );
     let bodyBackground = document.querySelector( "#body" );
    menuIcon.addEventListener( "click",()=> {
      menu.classList.contains('open') ? menu.classList.remove('open') : menu.classList.add('open');
    });

  </script>

</body>

app/views/shared/_navbar-home.html.erb
<nav class="navbar-home">
  <div class="container d-flex justify-content-between align-items-center">
    <%= image_tag("logo-blue.png", alt: "Bibtome Logo", class: "logo logo-blue")%>
    <%= image_tag("logo-white.png", alt: "Bibtome Logo white", class: "logo logo-white")%>
    <ul class="navbar">
      <li><%= link_to "Über uns", root_path, class: "btn btn-nav-link" %></li>
      <!-- <li><%#= link_to "Team", root_path, class: "btn nav-link" %></li> -->
      <li><%= link_to "Kontakt", root_path, class: "btn btn-nav-link" %></li>
      <% if user_signed_in? %>
        <%= render "shared/user_avatar" %>
        <i class="fas fa-ellipsis-v dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
        <%= render "shared/dropdown" %>
      <% else %>
        <li><%= link_to "Einloggen", new_user_session_path, class: "btn btn-nav-link" %></li>
        <li><%= link_to "Registrieren", new_user_registration_path, class: "btn btn-primary" %></li>
      <% end %>
    </ul>

    <!-- Navbar for Mobile devices only -->
    <div class="fake-hamburger">
      <i class="fas fa-bars"></i>
    </div>
    <%= render "shared/menu" %>
  </div>
</nav>

app/views/shared/_navbar_shared.html.erb
<nav class="shared-navbar">
  <div class="container larger-devices d-flex justify-content-between align-items-center">
      <%= link_to root_path do %>
        <%= image_tag("logo-blue.png", alt: "Bibtome Logo", class: "logo logo-blue")%>
      <% end %>
      <ul class="navbar">
        <li><%= link_to "Tag registrieren", register_input_path, class: "btn btn-nav-link" %></li>
        <li><%= link_to "Zurückgeben", finder_input_path, class: "btn btn-nav-link" %></li>
        <li><%= link_to "Über uns", root_path, class: "btn btn-nav-link" %></li>
        <!-- <li><%#= link_to "Team", root_path, class: "btn nav-link" %></li> -->
        <li><%= link_to "Kontakt", root_path, class: "btn btn-nav-link" %></li>
        <% if user_signed_in? %>
          <%= render "shared/user_avatar" %>
          <i class="fas fa-ellipsis-v dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <%= render "shared/dropdown" %>
        <% else %>
          <li><%= link_to "Einloggen", new_user_session_path, class: "btn btn-nav-link" %></li>
          <li><%= link_to "Registrieren", new_user_registration_path, class: "btn btn-primary" %></li>
        <% end %>
      </ul>

      <!-- Navbar for Mobile devices only -->
      <%= render "shared/menu" %>
    </div>
</nav>

app/views/shared/_user_avatar.html.erb
<div class="btn-group">
  <div class="user-avatar small">
    <h4><%= current_user.first_name[0] unless current_user.first_name.nil? %></h4>
  </div>
</div>