config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

app/controllers/tag_registers_controller.rb
class TagRegistersController < ApplicationController
  before_action :authenticate_user!

  def update
    @tag = Tag.find_by(code: params[:code].downcase)
    if @tag.nil?
      @error = "* Code not found"
      #flash[:alert] = "Code not found."
      render :register_input
    elsif @tag.registered == false
      @tag.registered = true
      @tag.user = current_user
      @tag.save
      redirect_to register_success_path(tag: @tag)
    elsif @tag.registered ==   true
      # flash.alert = "Code is already registered."
      @error = "* Code is already registered"
      render :register_input
    end
  end

  def register_input
  end

  def update_category
    @tag = Tag.find_by(code: params[:code.downcase])

    if params.include?(:category_dropdown)
      @tag.update(category: params[:category_dropdown])
      redirect_to dashboard_path
      flash[:notice] = "Category #{params[:category_dropdown]} assigned"
    else
      @tag.update(category: params[:item_select])
    end
  end

  def successful_registration
    @tag = Tag.find(params[:tag])
  end

end

app/views/tag_registers/register_input.html.erb
<!-- Shared Navbar -->
<%= render "shared/navbar_shared" %>

<div class="auth-session register-tag bg-white">
  <div class="auth-session-container">
    <h2 class="mb-4">Register Tag</h2>
    <p>Please enter your code below:</p>

    <div class="form-inputs">
      <%= form_tag update_register_input_path, method: :patch do %>
        <div class="errors">
          <% if @error %>
            <%= @error %>
          <% end %>
        </div>
        <%= text_field_tag :code,
                    params[:code],
                placeholder: "Enter your code here",
                      class: "form-control mb-2"%>
        <%# if current_user == nil %>
          <%#= submit_tag "Register now",class: "btn btn-bib btn-green btn-form btn-margin disabled" %>
        <%# else %>
        <%= submit_tag "Register now",class: "btn btn-primary" %>
        <%# end %>
      <% end %>
    </div>
    <p class="info">By registering your tag, you are increasing your chances to get back your lost belongs.</p>
  </div>
</div>

app/views/tag_registers/successful_registration.html.erb
<!-- Shared Navbar -->
<%= render "shared/navbar_shared" %>

<div class="auth-session h-full successfully-registration bg-white">
  <div class="auth-session-container">
    <div class="info-container">
      <%= image_tag("info-success-icon", alt: "Information icon", class: "info-icon")%>
      <span class="text-success">Your tag with ID <b><%= @tag.code.upcase %></b> was successfully registered</span>
    </div>
    <h3 class="mb-0">Which item do you want to secure?</h3>
    <p class="mb-2">Please, select the item you do like to associate to your tag:</p>


    <div class="radio-box-container">
      <div class="radio-boxs">
        <%= form_tag update_register_category_path, method: :patch do %>
          <%= hidden_field_tag :code, @tag.code %>
          <%= radio_button_tag :item_select, "Laptop", false, :onclick => "this.parentNode.submit();" %>
          <%= image_tag("laptop-icon", alt: "Laptop icon", class: "category-icon")%>
          <span>Laptop</span>
          <div class="divider"></div>
          <%= radio_button_tag :item_select, "Phone", false, :onclick => "this.parentNode.submit();" %>
          <%= image_tag("phone-icon", alt: "Phone icon", class: "category-icon")%>
          <span>Phone</span>
          <div class="divider"></div>
          <%= radio_button_tag :item_select, "Keys", false, :onclick => "this.parentNode.submit();" %>
          <%= image_tag("key-icon", alt: "Keys icon", class: "category-icon")%>
          <span>Keys</span>
          <div class="divider"></div>
          <%= radio_button_tag :item_select, "Bag", false, :onclick => "this.parentNode.submit();" %>
          <%= image_tag("backpack-icon", alt: "Bag icon", class: "category-icon")%>
          <span>Bag</span>
        <% end %>
      </div>
    </div>

    <h3 class="mb-0">By default finders can see your phone number.</h3>
    <a href="#" class="link mt-0">Want to change this setting?</a>

    <div class="buttons-container">
      <%= link_to "Register another tag", register_input_path, class: "btn btn-primary"%>
      <!-- replace user path by correct (future) path to user dashboard -->
      <%= link_to "Visit your dashboard", dashboard_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

<!-- Shared Footer -->
<%= render "shared/footer" %>