config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user, optional: true
  has_many :finders
  #after_initialize :set_code
  before_validation(on: :create) do
    self.code = SecureRandom.hex(3).downcase
  end
  after_create :set_registration, on: [ :create ]
  has_one_attached :qr
  validates :code, uniqueness: true, presence: true
  #after_create_commit :generate_image

  private

  # def generate_qr
  #   qrcode = RQRCode::QRCode.new("https://www.bibto.me/qr/#{self.code}")

  #   png = qrcode.as_png(
  #     bit_depth: 1,
  #     border_modules: 0,
  #     color_mode: ChunkyPNG::COLOR_GRAYSCALE,
  #     color: '#424C6A',
  #     file: nil,
  #     fill: 'white',
  #     module_px_size: 6,
  #     resize_exactly_to: false,
  #     resize_gte_to: true,
  #     size: 300
  #   )

  #   file = Tempfile.new(["qr-#{self.code}", ".png"])
  #   IO.binwrite(file, png.to_s)
  #   file.rewind
  #   file.close

  #   self.qr.attach(io: File.open(file), filename: "qr-#{self.code}.png")

  #   file.unlink
  # end

  def set_code
    self.code = SecureRandom.hex(3).downcase
  end

   def generate_image
   # @tag = Tag.new(code: SecureRandom.hex(3).downcase, registered: false)
    url = URI("https://qrcode-monkey.p.rapidapi.com/qr/custom")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Post.new(url)
    request["x-rapidapi-host"] = 'qrcode-monkey.p.rapidapi.com'
    request["x-rapidapi-key"] = ENV['RAPIDAPI_KEY']
    request["content-type"] = 'application/json'
    request["accept"] = 'application/json'

    request.body = "{
                  \"data\":\"https://www.bibto.me/qr/#{self.code}\",
                  \"config\":{
                  \"body\":\"round\",
                  \"eye\":\"frame13\",
                  \"eyeBall\":\"ball14\",
                  \"erf1\":[],
                  \"erf2\":[],
                  \"erf3\":[],
                  \"brf1\":[],
                  \"brf2\":[],
                  \"brf3\":[],
                  \"bodyColor\":\"#3F4C6A\",
                  \"bgColor\":\"#FFFFFF\",
                  \"eye1Color\":\"#3F4C6A\",
                  \"eye2Color\":\"#3F4C6A\",
                  \"eye3Color\":\"#3F4C6A\",
                  \"eyeBall1Color\":\"#3F4C6A\",
                  \"eyeBall2Color\":\"#3F4C6A\",
                  \"eyeBall3Color\":\"#3F4C6A\",
                  \"gradientColor1\":\"#3F4C6A\",
                  \"gradientColor2\":\"#3F4C6A\",
                  \"gradientType\":\"linear\",
                  \"gradientOnEyes\":false,
                  \"logo\":\"https://res.cloudinary.com/dyuwip9bs/image/upload/v1587555929/bibtome/qr/logo/Group_3_2_vbumpc.png\",
                  \"logoMode\":\"clean\"},
                  \"size\":300,
                  \"download\":true,
                  \"file\":\"png\"}"

    response = http.request(request)
    result = JSON.parse(response.body)
    result_hash = result["imageUrl"]
    imglink = "https:#{result_hash}"

    Cloudinary::Uploader.upload(imglink, :folder => "bibtome/qr/", :resource_type => "image", :public_id => "#{self.code}",
      :transformation => [
        {:width => 340, :height => 340, :crop => "crop"},
        {:radius => 10}])

    self.save
  end

  def set_registration
    self.registered = false
  end
end

app/controllers/tags_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'json'
require 'open-uri'

class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:update_registration]

  def create
    @tag = Tag.new(code: SecureRandom.hex(3).downcase, registered: false)

    # url = URI("https://qrcode-monkey.p.rapidapi.com/qr/custom")

    # http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    # request = Net::HTTP::Post.new(url)
    # request["x-rapidapi-host"] = 'qrcode-monkey.p.rapidapi.com'
    # request["x-rapidapi-key"] = ENV['RAPIDAPI_KEY']
    # request["content-type"] = 'application/json'
    # request["accept"] = 'application/json'

    # request.body = "{
    #               \"data\":\"https://www.bibto.me/qr/#{@tag.code}\",
    #               \"config\":{
    #               \"body\":\"round\",
    #               \"eye\":\"frame13\",
    #               \"eyeBall\":\"ball14\",
    #               \"erf1\":[],
    #               \"erf2\":[],
    #               \"erf3\":[],
    #               \"brf1\":[],
    #               \"brf2\":[],
    #               \"brf3\":[],
    #               \"bodyColor\":\"#3F4C6A\",
    #               \"bgColor\":\"#FFFFFF\",
    #               \"eye1Color\":\"#3F4C6A\",
    #               \"eye2Color\":\"#3F4C6A\",
    #               \"eye3Color\":\"#3F4C6A\",
    #               \"eyeBall1Color\":\"#3F4C6A\",
    #               \"eyeBall2Color\":\"#3F4C6A\",
    #               \"eyeBall3Color\":\"#3F4C6A\",
    #               \"gradientColor1\":\"#3F4C6A\",
    #               \"gradientColor2\":\"#3F4C6A\",
    #               \"gradientType\":\"linear\",
    #               \"gradientOnEyes\":false,
    #               \"logo\":\"https://res.cloudinary.com/dyuwip9bs/image/upload/v1587555929/bibtome/qr/logo/Group_3_2_vbumpc.png\",
    #               \"logoMode\":\"clean\"},
    #               \"size\":300,
    #               \"download\":true,
    #               \"file\":\"png\"}"

    # response = http.request(request)
    # result = JSON.parse(response.body)
    # result_hash = result["imageUrl"]
    # imglink = "https:#{result_hash}"

    # Cloudinary::Uploader.upload(imglink, :folder => "bibtome/qr/", :resource_type => "image", :public_id => "#{@tag.code}",
    #   :transformation => [
    #     {:width => 340, :height => 340, :crop => "crop"},
    #     {:radius => 10}])

    @tag.save
    # download = open(imglink)
    # file = Tempfile.new(["#{@tag.code}", ".png"])
    # IO.binwrite(file, download.to_s)
    # file.rewind
    # file.close
    # @tag.qr.attach(io: File.open(file), filename: "#{@tag.code}.png")
    # file.unlink
  end

  def update_registration(tag)
    if @tag.registered == true
      render template: #'/registration'
      flash.alert = "Code already registered."
    elsif @tag.registered == false
      @tag.registered = true
      @tag.user = current_user
      @tag.save
      render :successful_registration, locals: { tag: @tag }
    else
      render template: 'tags/registration'
      flash.alert = "Code not found."
    end
  end

  def return_tag_verification
    @tag = Tag.find_by(code: params[:code])

    if @tag && @tag.registered = true
      redirect_to new_finder_path(tag: @tag)
    else
      if !@tag
        @error = "Wrong tag code! Please insert a valid code."
        render  "pages/return_item", :locals => { :error => @error }
      elsif @tag.registered == false
        @error = "Tag containing this code hasn't been yet registered."
        render  "pages/return_item", :locals => { :error => @error }
      end
    end
  end

  def scan_code
    uri = request.original_url
    scanned_code = URI(uri).path.split('/').last
    @tag = Tag.find_by(code: scanned_code)
    if @tag.registered == true
      return_tag_verification
    elsif @tag.registered == false
      update_registration(@tag)
    end
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.category = params[:category]
    @tag.save
    flash[:notice] = "Category set"
    render :successful_registration
  end

  def registration
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:code, :category)
  end
end

app/views/tags/registration.html.erb
<div class="page-title">
  <div class="container">
    <h2 class="text-center">Good to see you!</h2>
    <%= link_to (image_tag "return.png", alt: "alttext", class: "btn-go-back"), :back %>
  </div>
</div>

<div class="container">
  <h3>To register your tag, please enter your code below</h3>
   <%= form_tag update_registration_path, method: :post do %>
    <%= text_field_tag :code,
      params[:code],
      class: "form-control bib-form-styling",
      placeholder: "Enter your code here"
    %>
    <%= submit_tag "Register now", class: "btn btn-bib btn-green btn-form btn-margin" %>
  <% end %>

</div>

app/views/tags/successful_registration.html.erb
<div class="container">


  <div class="text-center mb-3">
   <%= image_tag "icon_checked_green.svg", alt: "alttext"%>
  </div>
  <h3 class="text-center mb-3">Code: <span style="color: $c1;"><%= @tag.code %></span><br>was successfully registered</h3>
  <h4 class="text-center">Select category:</h4>

  <div class="category-grid">


      <div class="category-card">
        <%= form_tag tag_path(@tag), method: :patch do %>
        <%= hidden_field_tag :category, "Laptop" %>
          <%= submit_tag "Laptop", class: "btn" %>
        <% end %>
      </div>

      <div class="category-card">
        <%= form_tag tag_path(@tag), method: :patch do %>
        <%= hidden_field_tag :category, "Phone" %>
          <%= submit_tag "Phone", class: "btn" %>
        <% end %>
      </div>


      <div class="category-card">
        <%= form_tag tag_path(@tag), method: :patch do %>
        <%= hidden_field_tag :category, "Keys" %>
          <%= submit_tag "Keys", class: "btn" %>
        <% end %>
      </div>

      <div class="category-card">
        <%= form_tag tag_path(@tag), method: :patch do %>
        <%= hidden_field_tag :category, "Bag" %>
          <%= submit_tag "Bag", class: "btn" %>
        <% end %>
      </div>

  </div>

  <br>

  <h4>Finders can contact you via:</h4>
  <div class="d-inline">
    <strong class="mr-2">Phone:</strong><%=current_user.phone%> <!-- change to current user -->
  </div>
  <br>
  <%= link_to "Change your data", edit_user_registration_path, :class => "ml-0" %>
  <div>
    <%= link_to "Register another tag", tag_registration_path, :class => "btn btn-bib btn-green btn-form my-2" %>
    <!-- replace user path by correct (future) path to user dashboard -->
    <%= link_to "Visit your dashboard", user_path(current_user.id), :class => "btn btn-bib btn-grey btn-form my-2" %>
  </div>
</div>