config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
  devise_for :users

  get "/dashboard", to: "dashboard#show"
  post 'twilio/voice' => 'twilio#voice'

  root to: 'pages#home'


  get '/qr/:code', to: 'splitters#split_users', as: :split_users
  get 'components', to: 'pages#components', as: :components

  resources :tag_registers, only: :edit
  patch 'tag_registers/update', to: "tag_registers#update", as: :update_register_input
  patch 'tag_registers/update_category', to: "tag_registers#update_category", as: :update_register_category
  get 'tag_registration_input', to: "tag_registers#register_input", as: :register_input
  get 'register_success', to: 'tag_registers#successful_registration', as: :register_success

  resources :tag_finders, only: [:new, :create]
  get 'tag_return_input', to: 'tag_finders#finder_input', as: :finder_input
  get '/finders/thank-you', to: 'tag_finders#thank_you', as: :finder_thank_you
  # get '/thank-you', to: 'pages#thank_you', as: :thank_you
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# link_to scan_code_path(qr_code: 'kdlkjfd')

app/controllers/tag_finders_controller.rb
class TagFindersController < ApplicationController
before_action :authenticate_user!, except: [:new, :create, :thank_you, :finder_input]

   def new
      if params.include?(:code)
        @tag = Tag.find_by(code: params[:code.downcase])
        if @tag.nil? || @tag.user.nil?
          @error = "* Code not found"
          render :finder_input
        end
      elsif params.include?(:format)
        @tag = Tag.find_by(id: params[:format.downcase])
        if @tag.nil? || @tag.user.nil?
          @error = "* Code not found"
          render :finder_input
        end
      end
    @finder = Finder.new
  end

  def create
    @tag = Tag.find_by(id: params[:format])
    @finder = Finder.new(finder_params)
    @finder.tag = @tag
    @transformed_number = @tag.user.phone.starts_with?("0") ? @tag.user.phone = "+49" + "#{@tag.user.phone[1..-1]}" : @tag.user.phone
    if @finder.save
      full_message = "Your #{@tag.category} was found: Finder's info: #{@finder.phone} - #{@finder.email} Message: #{@finder.message}"
      ########## ------------------
      
      TwilioController.send_message(@transformed_number, full_message)
      ########### ------------------
      UserMailer.tag_found(@tag, @finder, full_message).deliver_now
      redirect_to finder_thank_you_path(@tag)
    else
      render :new
    end

    # mail = FinderMailer.with(user: @finder.tag.user, finder: @finder, tag: @finder.tag).notification
    # mail.deliver_now

  end

  def finder_input
  end

  def thank_you
    @tag = Tag.find_by(id: params[:format])

  end

  private

  def finder_params
    params.require(:finder).permit(:phone, :email, :message)
  end
end

app/views/tag_finders/_contact_form.html.erb
<p class="mb-2 text-center">Leave your contact info & get contacted by <%= @tag.user.first_name %></p>

<%= simple_form_for [@tag, @finder] do |f| %>
  <%= f.error_notification %>
​  <div class="form-inputs">
    <%= f.input :phone,
                placeholder: 'Your phone',
                label: "Your phone",
                required: false %>
    <%= f.input :email,
                label: "Email address",
                placeholder: 'Your Email',
                required: false,
                input_html: { autocomplete: "email"}
                 %>
    <%= f.input :message,
                label: "Your message",
                placeholder: 'Message',
                required: false
                %>
    <%= f.input :tag, :as => :hidden, :input_html => { :value => params[:format] } %>
    <%= f.button :submit, "Share my contact info", class: "btn btn-primary mb-4" %>
​  </div>
<% end %>

app/views/tag_finders/finder_input.html.erb
<!-- Shared Navbar -->
<%= render "shared/navbar_shared" %>

<div class="auth-session finder-input bg-white">
  <div class="auth-session-container">
    <h2 class="mb-4">Return Item</h2>
    <p>Please insert the tag ID to proceed verification:</p>

    <div class="form-inputs">
      <%= form_tag new_tag_finder_path, method: :get do %>
        <div class="errors">
          <% if @error %>
            <%= @error %>
          <% end %>
        </div>
        <%= text_field_tag :code,
                    params[:code],
                   required: :true,
                placeholder: "Enter your code here",
                      class: "form-control mb-2"%>
        <%= submit_tag "Send code",class: "btn btn-primary" %>
      <% end %>
    </div>
    <h3 class="mt-5 text-center">Need help? <a href="#">Contact us.</a></h3 class="mt-5 text-center">
  </div>
</div>

app/views/tag_finders/new.html.erb
<!-- Shared Navbar -->
<%= render "shared/navbar_shared" %>

<div class="finder-contact auth-session finder-input d-on-sm bg-white">
  <div class="auth-session-container">
    <h2 class="text-center">You are a hero!</h2>
    <h4 class="text-center">You have found <%= @tag.user.first_name %>´s <%= @tag.category %>.</h4>

    <% if @tag.category != "Phone" %>

      <% if @tag.user.phone && @tag.user.shared_phone %>
        <p class="text-center">Contact <%= @tag.user.first_name %> directly: <%= @tag.user.phone %></p>
       <!--  <div class="buttons-container">
          <#%= link_to "I will reach out to #{@tag.user.first_name}", finder_thank_you_path(@tag), class: "btn btn-primary mt-2", html: {width: "fit-content"}%>
        </div> -->
        <h4 class="mt-3 text-center">OR</h4>
<!--         <div class="switch-container">
          <label id="checky" class="switch mr-2">
            <input type="checkbox" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <span class="slider round"></span>
          </label>
          <h4 class="share-contact">Share my contact info with <%= @tag.user.first_name %>!</h4>
        </div> -->
<!--         <div class="collapse" id="collapseExample">
 -->          <%= render "contact_form" %>
        <!-- </div> -->
      <% else %>
      <!-- REMOVING d-flex before justi... -->
        <div class="justify-content-center">
          <%= render "contact_form" %>
        </div>
      <% end %>

    <% else %>
     <div class="justify-content-center">
       <%= render "contact_form" %>
     </div>
   <% end %>
  </div>

</div>

app/views/tag_finders/return_item.html.erb
<div class="container">
  <div class="my-5 mx-2">
    <div class="mb-5 pb-4 back-arrow-position-fix">
      <h3 class="text-center">Contact Details</h3>
        <%= link_to (image_tag "return.png", class: "btn-go-back"), "#" %>
    </div>

    <h4>
      You are a hero! ❤️ <br>
      You have found <%= @tag.user.first_name %>´s bag <br>
      <% if @tag.user.phone && @tag.user.shared_phone %>
        Please contact him/her here: <%= @tag.user.phone %>
      <% end %>
    </h4>
  <%# raise %>
    <div class="mt-5">
       <%= simple_form_for @finder do |f| %>
          <%= f.input :phone,
                      placeholder: 'Phone number',
                      label: false,
                      required: false,
                      autofocus: true,
                      input_html: { autocomplete: "email", class: "bib-form-styling btn-block py-3 px-4 mb-3" }
                      %>
          <%= f.input :email,
                      label: false,
                      placeholder: 'Email',
                      required: false,
                      input_html: { autocomplete: "email", class: "bib-form-styling btn-block py-3 px-4 mb-3" }
                       %>
          <%= f.input :message,
                      label: false,
                      placeholder: 'Message',
                      required: false %>
          <%= f.input :tag, :as => :hidden, :input_html => { :value => params[:tag].to_i } %>

          <%= f.button :submit, "Share information with owner", class: "btn btn-bib btn-green btn-block py-3" %>
      <% end %>
    </div>

    <h5 class="text-center mt-5">Need help?<span style="color: #FDD365">Click here.</span></h5>
  </div>
</div>

app/views/tag_finders/show.html.erb
<h1>You are a great human being</h1>

<h2>your honest and upright behavoir made this world better</h2>

<h3>If you want to know more about our mission and service then click the button below</h3>

<a href="/">Learn more (Home)</a>

app/views/tag_finders/thank_you.html.erb
<!-- Shared Navbar -->
<%= render "shared/navbar_shared" %>

<div class="auth-session finder-input d-on-sm bg-white">
  <div class="auth-session-container text-center thank-you">
    <h2 class="text-center">Thank you</h2>
    <h3>You just made the world a better place!</h3>
    <p>We notified <b><%= @tag.user.first_name %></b> with your contact details.</p>
    <h3 class="mt-5 mb-3">What is <b>bibto.me</b>?</h3>
    <%= link_to "Check it out", root_path, class: "btn btn-primary" %>
  </div>
</div>